# Generated by Django 5.1.2 on 2024-12-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordem_de_servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=12)),
                ('p_a', models.CharField(max_length=9)),
                ('p_c', models.CharField(max_length=9)),
                ('operacao', models.CharField(max_length=30)),
                ('n_operacao', models.CharField(max_length=4)),
                ('nome_pc', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=100)),
                ('uo', models.CharField(max_length=3)),
                ('fixacao', models.CharField(max_length=15)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
