# Generated by Django 5.1.2 on 2024-12-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gerenciamento', '0001_initial'),
    ]

    operations = [
    ]
